### ISSUE TITLE
Steam checklist

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#2041]
# WIP

# 0. Finish features we want to finish according to plan
 
- [x] complete plan https://docs.google.com/spreadsheets/d/1hguD2MwCXArrURovRx_4zf5T4FkchCWtpIljIae6DAw/edit#gid=0
- [x] feature freeze.

# 1. Initial QA pass 
At least 2 different skilled people should do this, one of them on ati

 - [x] reset ZK settings to defaults (delete steam copy) 
 - [x] create a new steam account
 - [x] download fresh copy of ZK 

###  Site and texts
 - [x] does it look reasonable unlogged or logged in? 
 - [x] do the buttons and texts make sense? 
 - [x] can I find the information needed? 
 - [ ] ~~is there a proper guide that teaches advanced game controls and hidden hotkeys?~~
 - [x] nothing odd or ugly?

### Lobby 
 - [x] does everything start properly and shows reasonable initial state?
 - [x] do the text make sense and avoid confusion? ("download" vs "online" in replays)
 - [ ] ~~can a person with low skill english find a way around?~~
 - [x] is it easy to do basic things? Start skirmish, start campaign, find MP battle? 
 - [x] is it easy to change basic settings? 

### Game 
 - [x] does everything look ok on different visual settings (low, medium, high, ultra) on both ATI and NVIDIA? (Water, shields, jets, air distortions etc)
 - [x] do initial settings match online tutorials and guides? 
 - [x] is it easy to find a way around and change basic settings? 
 - [x] is it easy to find a chat or other means of communication? 
 - [x] are there any traps? (Buttons that change language to non existing one, settings not working or screwing gui too much?)
 - [ ] does the entire campaign work? 
 - [ ] does entire campaign work with coop?

### Server
 - [x] repeat load test with fake users, evaluate lobby and server performance

# 2. Halt all work, correct only issues from QA pass

- [x] are all serious issues fixed?

# 3. PR material finalization phase

 - [x] allow only "safe" changes in repos (balance tweaks)
 - [ ] ~~A/B test trailer candidates~~
 - [ ] ~~A/B test screenshot/banner~~
 - [x] finalize PR materials (text, pics) on site
 - [x] finalize steam store page
 - [x] finalize PR materials on presskit
 - [x] select release date T0, at least 1 week ahead
 - [x] update information in existing references (Wiki, indieDB)
 - [x] fill information in new external sites, Co-OP sites like co-optimus etc

# 4. Release date announcement

 - [x] allow 0 changes to repos, except critical hotfixes
 - [x] put a release countdown on site
 - [x] mail opinion makers, youtubers and press with concrete easy to digest information (steam key, info about game, screenshots, release date)
 - [x] announce release date to our community  (try to reach FB, old players, spring)
 - [x] FB
 - [x] Twitter
 - [x] Old steam ZK group
 - [x] Spring
 - [ ] Itch
 - [ ] Moddb
 - [ ] try to form "newbie assist" volunteers which will create friendly and helpful environment on release
 - [x] ask people to install the game on steam on release and vote us up on release date

# 5. Release date

 - [x] prepare backup server for possible emergency hotswap, with older ZK DB state 
 - [ ] verify server state and reboot it
 - [ ] shut down non-essential services (test site)
 - [ ] release on steam 
 - [ ] monitor HW, be there to assist and guide

**Comment by Connetable** [comment]
I can help with the QA pass but 1) I am rather forgiving, so I am perhaps not representative of the average steam user and 2) as I am accustomed to the lobby for so long I might miss some things that would feel awkward for new players.

**Comment by Connetable** [comment]
Anyway tell me if I can start the QA

**Comment by Licho1** [comment]
Yeah! We are still working on final tweaks for the game and stuff..

**Comment by GoogleFrog** [comment]
@Connetable I'd like to begin now. If you have ATI it would be especially helpful. Otherwise, all fresh installs are helpful. A video would be good so more people can spot issues.

**Comment by Licho1** [comment]
I do have ATI on secondary PC, its old PC though

**Comment by Connetable** [comment]
Ok I dowloaded the game on steam and installed it. I had no problem. I have videos of it but they show nothing of interest. 
[QA Pass - Connetable.docx](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/1885494/QA.Pass.-.Connetable.docx)

**Comment by KingRaptor** [comment]
Tried various things, here's what I encountered: https://pastebin.com/xr1dDTvY

**Comment by Connetable** [comment]
I did a fresh install again and I don't have the mouse edge bug. And Chobby opens automatically on Community tab with awards shown. Seems that problems I had are not going to reproduce on other pcs so let's consider it solved.

**Comment by GoogleFrog** [comment]
Chobby intentionally does not open the community tab on the first launch. I don't want to attract players onto the internet before they have tried the game itself.

**Comment by Licho1** [comment]
Dunno about community .. i think its important to show game is alive.

**Comment by Sortale** [comment]
tested on steam new account fresh install ATI GPU. single player, skirmish, multiplayer, replay seem to work fine.

**Comment by sprunk** [comment]
:steam_locomotive:
