### ISSUE TITLE
Pragmatic Planetwars Tasks

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2064]
Attacking and turns.
- [x] If the active attacking faction has no valid targets then they should effectively miss their turn (https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1855). I think the current system gives them a random target.
- [x] The turn timer for a faction with no valid targets should be set to 2 minutes.
- [ ] ~~If you forfeit your turn and no faction has any valid targets then increment the turn timer. This check should ignore alliances, so is equivalent to checking whether any faction has an active wormhole facing any other planet (https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1855#issuecomment-341586467).~~

Economy and infrastructure.
- [x] Add the ability to rush the activation of structures, for a price (https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1705#issuecomment-293632846). Disabled (i.e. powering up) structures should have a button which players can use to spend X metal to activate the structure next turn. X should be a DB key which is settable per-structure.
- [x] Remove planet buster and string connector.
- [x] Remove energy to metal conversion.
- [x] Add "rush time" DB entry. This sets the number of turns until a rushed structure is activated. Rush timer of zero means the structure is activated instantly with no economy tick required. It can be used for defenses, attacks, etc...

Diplomacy. For terminology, "X" is the sender of a treaty and "Y" is the receiver.
- [x] Check whether defense pact works (https://github.com/ZeroK-RTS/Chobby/issues/235).
- [x] Add two fields in treaty creation called "Us Collateral" and "Them Collateral", which is an amount of metal. X pays Us Collateral to send the treaty (https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1856#issuecomment-341856234). Y pays Them Collateral to accept the treaty. X is refunded Us Collateral if X cancels the proposal or Y rejects the proposal (both actions should be able to be performed). The diplomats (people with treaty creation power) can spend faction metal on collateral as if they had full quota.
- [x] Make treaties cancellable at any time. If one party cancels a treaty then the other party receives the collateral that both X and Y paid.
- [x] Treaties can still have a set turn limit. The collateral is refunded if a treaty expires with no cancellation.
- [x] If a faction cannot make per-turn costs of a treaty then the treaty is automatically broken. Remove the debt system.
- [ ] ~~Add a treaty effect that allows players from X to join attacks on Ys attack turn, exactly as if they were members of faction Y. Call the effect "Joint Attack".~~
- [x] Check that the effect in this ticket are implemented https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1697.
- [x] Make the IP and IP-per-turn treaty effects not care if there is insufficient IP to fulfill them. When there is insufficient IP just transfer all the IP without any ill-effects (i.e. acceptance blockage or auto-break).

Victory:
- [x] It should be impossible for a HQ planet to be neutral.
- [x] If any faction owns 2 HQs they should win.

**Comment by Licho1** [comment]
Forfeit your turn without attacking is complex (risky changes in PW logic, PW logic assumes some winner)
I think that with improved treaties this thing isnt needed, correct?

**Comment by Licho1** [comment]
Also I am not sure we have to remove buster, since it does not remove links now. Makes it into a chicken planet

**Comment by GoogleFrog** [comment]
What does TurnsToreactivate do? Planet buster needs removing. Forfeit your turn without attacking is required because treaties could get deadlocked.

**Comment by Licho1** [comment]
Planet buster is removed. 
TurnsToReactivate is turns to "rebuild" after destruction. Before it used simple multiplier (x2) to activate after bombing/planet loss. Now it is configurable per structure.

Treaties cannot get deadlocked, there will be cancel button. If there is temp deadlock timer will just stop and wait for people to cancel.

**Comment by GoogleFrog** [comment]
Hang on, can you describe the state machine that controls structure activation? What are all the ways to deactivate structures and how do they interact? Previously I thought that all activation was limited to a single timer.

Treaties can be deadlocked in the sense that everyone involved is highly encouraged not to break the deadlock for strategic reasons. It seems very silly that a treaty due to lapse in 3 turns would cause a very costly deadlock by 'chance'. Factions could also collude to bring about deadlocks.

**Comment by Licho1** [comment]
1) building structure 
 2) changing target for targetable structure (like guerilla gate)
 3) taking "abandoned" structure - for example by capturing neutral planet or taking over structure owned
 4) capturing structure from other faction by influence spread or diplomacy
 
 5) structure destroyed in-game
 6) attacker won in-game and structure was not activated


5 and 6 use longer timer than 1-4 because it involves violence

**Comment by GoogleFrog** [comment]
What about turning a structure on after a lack of energy last turn?

So 1-4 use one number and 5-6 use another number? Each are independently configurable in DB?

**Comment by Licho1** [comment]
yes.
If structure powered off after being active, "build" timer (1-4) is used.
