### ISSUE TITLE
Licho's important tasks todo

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#2872]
- [x] fix browser not opening for crash reports
 - [x] fix launcher not working or not downloading stuff on linux
 - [x] switch deployment system to github actions (remove teamcity)
 - [x] ~attempt to upload zero-k launcher to antivirus systems using some API~ <- it is now considered mostly harmless by removing self upgrade, unknown publisher persists
 - [x] increase maximum upload file size
 - [x] modoptions service for chobby .. internal name -> json
 - [x] add support for mapoptions
 - [x] solve the issue with replays and space -> thaw AWS glacial, migrate all to blobs or similar service
 - [ ] make rapid system server and migrate all data from spring web
 - [ ] add some GUI to let people upload and maintain their mods in rapid system
 - [ ] remake planetwars logic in accordance with latest GoogleFrog proposal
 - [x] figure out SQL server RAM issue or mitagate it (migrate to machine with 64GB ram or add automated sql server restarts)
 - [ ] daracas1 https://zero-k.info/Users/Detail/524391 contacts admins : hi, i donate a (silver donation) on steam yesterday, but it seem i dont have de contributor tag and the kudo associate to my contribution. (from 16.4.2022)
 - [ ] add eggs
 - [ ] add "portable" build automation 
 - [ ] improve "new version" detection for wrapper (do not scream for non-relevant changes)

**Comment by GoogleFrog** [comment]
@Licho1 could you look into autohosts losing their settings? I think something was done to save things in the database, but this messed up at some point. It would help with the ideas here http://zero-k.info/Forum/Thread/36294
